set(SDK_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/SDK)
set(SDK_PATH ${SDK_DIRECTORY}/StratifyLabs-SDK)

file(MAKE_DIRECTORY ${SDK_PATH})
set(DEPENDENCIES_DIRECTORY ${SDK_DIRECTORY}/dependencies)
file(MAKE_DIRECTORY ${DEPENDENCIES_DIRECTORY})

set(CMAKE_SDK_DIRECTORY ${DEPENDENCIES_DIRECTORY}/CMakeSDK)
if(NOT EXISTS ${CMAKE_SDK_DIRECTORY})
	execute_process(
		COMMAND git clone --branch main https://github.com/StratifyLabs/CMakeSDK.git
		WORKING_DIRECTORY ${DEPENDENCIES_DIRECTORY}
		)
endif()

file(MAKE_DIRECTORY ${CMAKE_SDK_DIRECTORY}/cmake_link)

set(ENV{SOS_SDK_PATH} ${SDK_PATH})
execute_process(
	COMMAND cmake ..
	WORKING_DIRECTORY ${CMAKE_SDK_DIRECTORY}/cmake_link
	)

execute_process(
	COMMAND cmake --build . --target install
	WORKING_DIRECTORY ${CMAKE_SDK_DIRECTORY}/cmake_link
	)

file(MAKE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/cmake_link)
