
// Do not edit this file. It was generated automatically with DesignLab.
// Don't try to build this file. Just copy and paste the parts you need to another source file.

#ifndef DESIGN_LAB_COMPONENTS_MYCOMPONENT2_HPP
#define DESIGN_LAB_COMPONENTS_MYCOMPONENT2_HPP


#include <lvgl/ObjectAccess.hpp>
#include <design/macros.hpp>


class MyComponent2 : public lvgl::ObjectAccess<MyComponent2> {
public:
  LVGL_OBJECT_ACCESS_DECLARE_CONSTRUCTOR(MyComponent2);



private:
  struct Names {
    DESIGN_DECLARE_NAME(main_column);
    DESIGN_DECLARE_NAME(main_heading);
    DESIGN_DECLARE_NAME(progress_bar);
    DESIGN_DECLARE_NAME(button_row);
    DESIGN_DECLARE_NAME(up_button);
    DESIGN_DECLARE_NAME(down_button);
    DESIGN_DECLARE_NAME(MySlider);
  };
};
#endif //DESIGN_LAB_COMPONENTS_MYCOMPONENT2_HPP;

